name: CI
on:
  # Run CI against all pushes (direct commits, also merged PRs), Pull Requests
  push:
    branches:
      - main
      - dev
  pull_request:
  # Run CI once per day (at 06:00 UTC)
  # This ensures that even if there haven't been commits that we are still testing against latest version of ansible-test for each ansible-base version
  schedule:
    - cron: '0 6 * * *'
  workflow_dispatch:
env:
  NAMESPACE: community
  COLLECTION_NAME: sap_libs

jobs:
  sanity:
    name: Sanity (Ⓐ${{ matrix.ansible }})
    strategy:
      matrix:
        ansible:
          - stable-2.15
          - stable-2.16
          - stable-2.17
          - stable-2.18
          - stable-2.19
          - devel

    runs-on: >-
      ${{ contains(fromJson(
          '["stable-2.13", "stable-2.14"]'
      ), matrix.ansible) && 'ubuntu-20.04' || 'ubuntu-latest' }}
    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Perform sanity testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          testing-type: sanity
        

  units:
    runs-on: >-
      ${{ contains(fromJson(
          '["stable-2.13", "stable-2.14"]'
      ), matrix.ansible) && 'ubuntu-20.04' || 'ubuntu-latest' }}
    name: Units (Ⓐ${{ matrix.ansible }}+py${{ matrix.python }})
    strategy:
      # As soon as the first unit test fails, cancel the others to free up the CI queue
      fail-fast: true
      matrix:
        include:
          - ansible: stable-2.15
            python: '3.11'
          - ansible: stable-2.16
            python: '3.11'
          - ansible: stable-2.17
            python: '3.12'
          - ansible: stable-2.18
            python: '3.12'
          - ansible: stable-2.19
            python: '3.13'
          - ansible: devel
            python: '3.13'

    steps:

      - name: Check out code
        uses: actions/checkout@v4

      - name: Perform unit testing
        uses: ansible-community/ansible-test-gh-action@release/v1
        with:
          ansible-core-version: ${{ matrix.ansible }}
          target-python-version: ${{ matrix.python }}
          testing-type: units

# Please consult the Readme for information on why we disabled integration tests temporarily.